### ISSUE TITLE
Broken str_replace behavior

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/zephir#802] opened 2015-03-02 18:53 UTC
In PHP str_replace accept array as first and second parameters, but in Zephir we can't use this feature:

```zep
	public static function doSomething()
	{
		var arr;

		let arr = ["a", "b", "c"];

		var_dump(str_replace(arr, "", "apple juice is amazing delicious"));
	}
```

This code produces "NULL".

Zephir 0.6.0a

**Comment by mruz** [comment] 2015-03-03 08:26
Duplicated https://github.com/phalcon/zephir/issues/732

**Comment by serg-deep** [comment] 2015-03-06 01:30
+1

**Comment by mruz** [comment] 2015-03-06 06:40
Temporarily you can use loop like in friendlyTitle https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/tag.zep#L1370

**Comment by SliceOfLife** [comment] 2015-03-06 09:45
Yes, yes, we can.
But this behavior violations broke ported PHP code in unexpected points without any compiler or parser warnings.

**Comment by nkt** [comment] 2015-03-07 13:45
Duplicate of #732

**Closed by nkt** 2015-03-07 13:45 UTC
