### ISSUE TITLE
Standart loop for

### ISSUE THREAD

**Issue by valVk** [phalcon/zephir#940] opened 2015-05-06 19:57 UTC
```php
		for (i = 0; i < length; i += limit) {
			let r[] = mb_substr(value, i, limit, charset);
		}
```

Zephir\ParseException: Syntax error in /freespace/sites/phalcon/zephir-projects/twigz/twigz/functional.zep on line 492

	  for (i = 0; i < length; i += limit) {
	------^

How can I use this syntax in scope of zephir?

Thanks.

**Comment by steffengy** [comment] 2015-05-06 20:00
Duplicate of #741

**Closed** 2015-05-06 20:01 UTC

**Comment by valVk** [comment] 2015-05-06 20:09
Thanks for pointing
