### ISSUE TITLE
A difficult problem that happend to me

### ISSUE THREAD

**Issue by SakuraZhang** [phalcon/zephir#1029] opened 2015-07-14 06:58 UTC
The code is like blew:
```php
namespace Test;
if(!defined('CONST_A')){
    defined('CONST_A','test');
}
class A{
    const TEST_V = CONST_A;
}
```
So when I try to use zephir to translate my PHP code ,I can't find a better way to solve this problem;
The question is that the zephir dosen't support define function.I find a way is that I can use the orignal C programming language.Now the code can compie succefully now,when I try to use it there is a PHP runtime error:bus error 

I wonder if someone have a better way to solve this problem.Thanks.

**Comment by SakuraZhang** [comment] 2015-07-15 07:35
Maybe there is no solution for this.

**Comment by steffengy** [comment] 2015-07-15 09:20
This is like an exact duplicate of #1026.

Therefor the same answer applies:
You need an entrypoint to run code in zephir,
you cannot run code without a scope.

That means you could for example move that code to an initialize method, which you call at the
start of your application lifetime, which performs
these checks, which relay on code being executed.

According to your problem description the problem lies with the defined function, which does not really match the code you provide, since you do something that's not possible in zephir (running code outside a function)

**Closed** 2015-07-15 11:16 UTC
