### ISSUE TITLE
zephir __call magic method bug

### ISSUE THREAD

**Issue by buildsufai** [phalcon/zephir#807] opened 2015-03-09 19:59 UTC
```
//a.zep
class a {
    public function __call(string methodName,array args) {
         var_dump(methodName);
    }
}
class b {
   public function say() {
        var a;
        let a = new a();
        a->GetXxXSSxx();
   }
}
// if call $a->GetXxXSSxx() , in the zephir,always lowercase
output: getxxxssxx
##################
call in php
output: GetXxXSSxx
```

**Comment by steffengy** [comment] 2015-03-09 20:01
Please use the search before posting issues.

Duplicate of #398 .

**Comment by buildsufai** [comment] 2015-03-09 20:05
@steffengy 

ok,thankyou ,seem like only the way....

**Comment by ovr** [comment] 2015-03-14 03:35
Closed via Duplicate

**Closed by ovr** 2015-03-14 03:35 UTC
